all:
	curl https://dl.dropboxusercontent.com/u/3091691/NNforMLL-lib/datasets.tar.gz -o datasets.tar.gz
	tar xvf datasets.tar.gz
	rm datasets.tar.gz

clean:
	rm -rf scene
	rm -rf yeast
	rm -rf emotions
	rm -rf nn-test
