all:
	curl https://dl.dropboxusercontent.com/u/3091691/NNforMLL-lib/dataset.tar.gz -o dataset.tar.gz
	tar xvf dataset.tar.gz
	rm dataset.tar.gz

clean:
	rm -rf scene
	rm -rf yeast
	rm -rf emotions
	rm -rf nn-test
